# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# list of jobs
jobs:
  chromatic:
    name: 'Run chromatic'
    runs-on: ubuntu-latest
    # job steps
    steps:
      - use: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm
        # Adds chromatic as a step in the workflow
      - uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
